"""update course model.

Revision ID: 43ad17ecd608
Revises: 60c36b862ec8
Create Date: 2023-03-22 23:45:27.175300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ad17ecd608'
down_revision = '60c36b862ec8'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_course_teacher_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_course_teacher_id_user', 'user', ['teacher_id'], ['id'])
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['teacher'], ['id'])
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
