"""update course model.

Revision ID: f82eac08710b
Revises: 43ad17ecd608
Create Date: 2023-03-23 00:05:02.587593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82eac08710b'
down_revision = '43ad17ecd608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
